#!/bin/bash

screen=$(xrandr | grep "connected" | cut -f1 -d " ")
brightness=$1
mode=$2

if (( $(echo "$1 < 0 || $1 > 1.5" | bc -l) ))
then
	echo "Brightness level should be a value between 0 and 1"
	exit 1
fi

if [ "$mode" == "night" ]
then
	xrandr --output $screen --gamma 1.1:0.9:0.5  --brightness $brightness
else
	xrandr --output $screen --gamma 1:1:1 --brightness $brightness
fi

