#!/bin/bash

screen=$(xrandr | grep "connected" | cut -f1 -d " ")
brightness=$1

if [ $1 -gt 1 || $1 -lt 0]
then
	echo "Brightnes level should be a value between 0 and 1"
	exit 1
fi

xrandr --output $screen --brightness $brightness
